{% set version = "4.0" %}
{% set build_number = 2 %}
{% set sha256 = "7f4e8ab608b3191c2b21e3f13c193f1344b40aba7738f78762f7b88f45e8ce03" %}

{% set llvm_version = "15.0.7" %}

package:
  name: pocl-core
  version: {{ version }}

source:
  - url: https://github.com/pocl/pocl/archive/refs/tags/v{{ version.replace(".rc", "-RC") }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - patches/1067.diff
      - patches/gh1277.patch

build:
  number: {{ build_number }}
  skip: true  # [win]
  script_env:   # [enable_cuda]
    - CUDA_HOME   # [enable_cuda]

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('cxx') }}                                   # [not osx]
    - clangxx_{{ target_platform }} {{ llvm_version }}.*      # [osx]
    - llvmdev {{ llvm_version }}.*       # [build_platform != target_platform]
    - clangdev {{ llvm_version }}.*      # [build_platform != target_platform]
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc
    - clhpp

    - llvmdev {{ llvm_version }}.*
    - clangdev {{ llvm_version }}.*
    - llvm {{ llvm_version }}.*
    - libclang-cpp {{ llvm_version }}.*
    - llvm-spirv-{{ llvm_version.split(".")[0] }}

    - zlib                               # [osx]
    - ld64 >=530                         # [osx]
  run:
    - llvm-spirv-{{ llvm_version.split(".")[0] }}
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - ld64 >=530                         # [osx]
    - {{ pin_compatible('libhwloc') }}
  run_constrained:
    - pocl {{ version }}.*

test:
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]

outputs:
  - name: pocl-core

  - name: pocl-cpu-minimal
    script: install-pkg.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-basic.so     # [unix]

  - name: pocl-cpu
    script: install-pkg.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - {{ pin_subpackage("pocl-cpu-minimal", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - {{ pin_subpackage("pocl-cpu-minimal", exact=True) }}
    test:
      requires:
        - pyopencl
        - curl
        - pocl-cpu
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-pthread.so     # [unix]
        # Remove apple icd so that only pocl is found
        - rm -f $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
        - export OCL_ICD_DEBUG=15                     # [linux]
        - export POCL_DEBUG=1
        - curl -O https://raw.githubusercontent.com/inducer/pyopencl/main/examples/demo.py
        - python demo.py

  - name: pocl-cuda
    build:
      skip: true  # [not enable_cuda]
    script: install-pkg.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda.so      # [unix]

  - name: pocl
    requirements:
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - {{ pin_subpackage("pocl-cpu", exact=True) }}
        - {{ pin_subpackage("pocl-cpu-minimal", exact=True) }}
        - {{ pin_subpackage("pocl-cuda", exact=True) }}         # [enable_cuda]
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-pthread.so   # [unix]
        - test -f $PREFIX/lib/pocl/libpocl-devices-basic.so     # [unix]
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda.so      # [enable_cuda]


about:
  home: http://portablecl.org/
  license: MIT
  license_file:
    - LICENSE
    - LLVM-License.txt
    - LICENSE_THIRDPARTY  # [osx]
  summary: Portable Computing Language -- a portable open source implementation of the OpenCL standard
  dev_url: https://github.com/pocl/pocl
  doc_url: http://portablecl.org/docs/html/

extra:
  feedstock-name: pocl
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
    - matthiasdiener
