{% set name = "pocl" %}
{% set version = "1.3" %}
{% set build_number = 2 %}
{% set sha256 = "6527e3f47fab7c21e96bc757c4ae3303901f35e23f64642d6da5cc4c4fcc915a" %}
{% set llvm_version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
  #- git_url: https://github.com/pocl/pocl.git
  #  git_rev: v1.3-RC3

    patches:
    # https://github.com/pocl/pocl/pull/708
    - 708.patch

build:
  number: {{ build_number }}
  skip: True  # [win]
  merge_build_host: True   # [cxx_compiler=='gxx']

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc
    - libtool
    - llvmdev =={{ llvm_version }}
    - clangdev =={{ llvm_version }}
    - lld =={{ llvm_version }}
    - libcxx                             # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - {{ pin_compatible('libhwloc') }}
    - libtool

test:
  requires:
    - pyopencl
    - curl
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    # Remove apple icd so that only pocl is found
    - rm $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
    - curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py
    - python demo.py

about:
  home: http://portablecl.org/
  license: MIT
  license_file: LICENSE
  summary: 'Portable Computing Language -- a CPU OpenCL implementation'
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
