{% set version = "7.1" %}

{% if llvm_version is not defined %}
{% set llvm_version = "0.0.0" %}
{% endif %}
{% if cuda_compiler_version is not defined %}
{% set cuda_compiler_version = "0.0" %}
{% endif %}

{% set cuda_major_version = cuda_compiler_version.split(".")[0] %}

package:
  name: pocl-core
  version: {{ version }}

source:
  - url: https://github.com/pocl/pocl/archive/refs/tags/v{{ version.replace(".rc", "-RC") }}.tar.gz
    sha256: 1110057cb0736c74819ad65238655a03f7b93403a0ca60cdd8849082f515ca25
    patches:
      - patches/0002-pocld.patch
      - patches/0003-switch-to-newer-find_package-CUDAToolkit-for-CUDA-12.patch
      # https://github.com/conda-forge/pocl-feedstock/pull/106#issuecomment-2467398973
      - patches/disable-cuda-test.patch
      - patches/ocl-icd-mac.diff   # [not linux]
      - patches/unistd-win.diff

build:
  number: 1
  skip: true  # [cuda_compiler_version == "11.8"]
  skip: true  # [enable_cuda and (cuda_compiler_version == "None")]
  skip: true  # [not enable_cuda and (cuda_compiler_version != "None")]
  script_env:
    - LLVM_VERSION_MAJOR={{ llvm_version.split(".")[0] }}
  ignore_run_exports_from:
    # we only need libcuda.so.1
    - {{ compiler('cuda') }}   # [enable_cuda]
    - cuda-version             # [enable_cuda]
    - cuda-driver-dev          # [enable_cuda]
    - cuda-cudart-dev          # [enable_cuda]
    - libxml2-devel

requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - {{ compiler('cxx') }}                                   # [not osx]
    - clangxx_{{ target_platform }} {{ llvm_version }}.*      # [osx]
    - {{ compiler('cuda') }}                                  # [enable_cuda]
    - llvmdev {{ llvm_version }}.*       # [build_platform != target_platform]
    - clangdev {{ llvm_version }}.*      # [build_platform != target_platform]
    - {{ stdlib("c") }}
  host:
    - libopencl-devel
    - libhwloc
    - clhpp
    - libxml2-devel
    - winpthreads-devel   # [win]
    - llvmdev {{ llvm_version }}.*
    - clangdev {{ llvm_version }}.*
    - llvm {{ llvm_version }}.*
    - libclang-cpp {{ llvm_version }}.*
    - llvm-spirv-{{ llvm_version.split(".")[0] }}  # [unix]
    - cuda-version {{ cuda_major_version }}.*  # [enable_cuda]
    - cuda-driver-dev                    # [unix and enable_cuda]
    - cuda-cudart-dev                    # [enable_cuda]
    - zlib                               # [osx or win]
    - ld64 >=530                         # [osx]
    - libjpeg-turbo
  run:
    - llvm-spirv-{{ llvm_version.split(".")[0] }}   # [unix]
    # See https://github.com/conda-forge/cctools-and-ld64-feedstock/issues/66
    # why we need the upper bound for ld64
    - ld64 >=530                         # [osx]
    - {{ pin_compatible('libhwloc') }}
  run_constrained:
    - pocl {{ version }}.*

test:
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}             # [unix]
    - if not exist %LIBRARY_BIN%\\pocl.dll exit 1   # [win]

outputs:
  - name: pocl-core

  - name: pocl-cpu-minimal
    script: install-pkg.sh  # [unix]
    script: install-pkg.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-basic${SHLIB_EXT}      # [unix]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-basic.dll exit 1     # [win]

  - name: pocl-cpu
    script: install-pkg.sh  # [unix]
    script: install-pkg.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - {{ pin_subpackage("pocl-cpu-minimal", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - {{ pin_subpackage("pocl-cpu-minimal", exact=True) }}
    test:
      requires:
        - pyopencl
        - curl
        - pocl-cpu
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-pthread${SHLIB_EXT}    # [unix]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-pthread.dll exit 1   # [win]
        # Remove apple icd so that only pocl is found
        - rm -f $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
        - export OCL_ICD_DEBUG=15                        # [linux]
        - export POCL_DEBUG=1                            # [unix]
        - set POCL_DEBUG=1                               # [win]
        - curl -O https://raw.githubusercontent.com/inducer/pyopencl/main/examples/demo.py
        - python demo.py

  - name: pocl-cuda
    build:
      skip: true  # [not enable_cuda]
    script: install-pkg.sh  # [unix]
    script: install-pkg.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
      run_constrained:
        - __cuda >={{ cuda_major_version }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda${SHLIB_EXT}       # [unix]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-cuda.dll exit 1      # [win]

  - name: pocl-remote
    script: install-pkg.sh  # [unix]
    script: install-pkg.bat  # [win]
    build:
      skip: true   # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-remote${SHLIB_EXT}     # [unix]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-remote.dll exit 1    # [win]

  - name: pocl
    requirements:
      host:
        # Need hwloc here for the pocl meta-package to have two hashes
        # Otherwise only one of them gets uploaded and the `exact=True`
        # conditions below prevent installations
        - libhwloc
      run:
        - {{ pin_subpackage("pocl-core", exact=True) }}
        - {{ pin_subpackage("pocl-cpu", exact=True) }}
        - {{ pin_subpackage("pocl-cpu-minimal", exact=True) }}
        - {{ pin_subpackage("pocl-remote", exact=True) }}       # [unix]
        - {{ pin_subpackage("pocl-cuda", exact=True) }}         # [enable_cuda]
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-pthread${SHLIB_EXT}     # [unix]
        - test -f $PREFIX/lib/pocl/libpocl-devices-basic${SHLIB_EXT}       # [unix]
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda${SHLIB_EXT}        # [unix and enable_cuda]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-pthread.dll exit 1    # [win]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-basic.dll exit 1      # [win]
        - if not exist %LIBRARY_BIN%\\pocl\\pocl-devices-cuda.dll exit 1       # [win and enable_cuda]
      downstreams:
        - pyopencl

about:
  home: http://portablecl.org/
  license: MIT
  license_file:
    - LICENSE.with.3rdparty
  summary: Portable Computing Language -- a portable open source implementation of the OpenCL standard
  dev_url: https://github.com/pocl/pocl
  doc_url: http://portablecl.org/docs/html/

extra:
  feedstock-name: pocl
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
    - matthiasdiener
