{% set name = "pocl" %}
{% set version = "1.3" %}
{% set build_number = 1 %}
{% set sha256 = "6527e3f47fab7c21e96bc757c4ae3303901f35e23f64642d6da5cc4c4fcc915a" %}
{% set llvm_version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
  #- git_url: https://github.com/pocl/pocl.git
  #  git_rev: v1.3-RC3

    patches:
    # Put binary paths built in pocl into a separate compilation unit
    # so that conda can successfully change them. (If they're not in
    # a separate compilation unit, the compiler has a habit of evaluating
    # strlen() and such at compile time.)
    - paths-in-separate-compilation-unit.patch

build:
  number: {{ build_number }}
  skip: True  # [win]
  merge_build_host: True   # [cxx_compiler=='gxx']

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc
    - libtool
    - llvmdev =={{ llvm_version }}
    - clangdev =={{ llvm_version }}
    - libcxx                             # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - {{ pin_compatible('libhwloc') }}

    # Needed for $PREFIX/lib/clang/8.0.0/include/opencl-c.h
    # FIXME: Slight overkill, as this brings in all of LLVM and Clang, for one
    # measly header file that we *actually* want.
    - clangdev =={{ llvm_version }}

    - libtool

test:
  #requires:
    #- pyopencl
    #- curl
    #- osx-pocl-opencl  # [osx]

  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    #- curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py
    #- python demo.py

about:
  home: http://portablecl.org/
  license: MIT
  license_file: LICENSE
  summary: 'Portable Computing Language -- a CPU OpenCL implementation'
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
