{% set name = "pocl" %}
{% set version = "3.1" %}
{% set build_number = 0 %}
{% set sha256 = "82314362552e050aff417318dd623b18cf0f1d0f84f92d10a7e3750dd12d3a9a" %}

{% set llvm_version = "14.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pocl/pocl/archive/refs/tags/v{{ version.replace(".rc", "-RC") }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - patches/1067.diff

build:
  number: {{ build_number }}
  skip: true  # [win]
  script_env:   # [enable_cuda]
    - CUDA_HOME   # [enable_cuda]

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('cxx') }}                                   # [not osx]
    - clangxx_{{ target_platform }} {{ llvm_version }}.*      # [osx]
    - llvmdev {{ llvm_version }}.*       # [build_platform != target_platform]
    - clangdev {{ llvm_version }}.*      # [build_platform != target_platform]
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc
    - clhpp

    - llvmdev {{ llvm_version }}.*
    - clangdev {{ llvm_version }}.*
    - llvm {{ llvm_version }}.*
    - libclang-cpp {{ llvm_version }}.*

    - zlib                               # [osx]
    - ld64 >=530                         # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - ld64 >=530                         # [osx]
    - {{ pin_compatible('libhwloc') }}

test:
  requires:
    - pyopencl
    - curl
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    # Remove apple icd so that only pocl is found
    - rm -f $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
    - export OCL_ICD_DEBUG=15                     # [linux]
    - curl -O https://raw.githubusercontent.com/inducer/pyopencl/main/examples/demo.py
    - python demo.py

outputs:
  - name: pocl

  - name: pocl-cuda
    build:
      skip: true  # [not enable_cuda]
    script: install-cuda.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("pocl", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda.so     # [unix]

about:
  home: http://portablecl.org/
  license: MIT
  license_file:
    - LICENSE
    - LLVM-License.txt
    - LICENSE_THIRDPARTY  # [osx]
  summary: Portable Computing Language -- a portable open source implementation of the OpenCL standard
  dev_url: https://github.com/pocl/pocl
  doc_url: http://portablecl.org/docs/html/

extra:
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
    - matthiasdiener
