{% set name = "pocl" %}
{% set version = "1.1" %}
{% set build_number = "2" %}
{% set sha256 = "1e8dd0693a88c84937754df947b202871a40545b1b0a97ebefa370b0281c3c53" %}
{% set llvm_version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{version}}.tar.gz
  sha256: {{ sha256 }}

  # git_url: https://github.com/pocl/pocl.git
  # git_rev: 09cf952f4eeb79825bfa8e09198cd4c6e106d0a0

  patches:
  # Put binary paths built in pocl into a separate compilation unit
  # so that conda can successfully change them. (If they're not in
  # a separate compilation unit, the compiler has a habit of evaluating
  # strlen() and such at compile time.)
  - paths-in-separate-compilation-unit.patch

  # Disable unneeded macro workaround
  - fix-macros.patch

  # MacOS fixes https://github.com/pocl/pocl/pull/628
  - fix-osx.patch

build:
  number: {{ build_number }}
  skip: True  # [not (unix or py>=35)]

requirements:
  build:
    - cmake
    - ocl-icd  # [linux]
    - libhwloc 1.*
    - libtool
    - pkg-config
    - llvmdev =={{ llvm_version }}
    - clangdev =={{ llvm_version }}
    - libcxx =={{ llvm_version }}
  run:
    - ocl-icd  # [linux]
    - clangdev =={{ llvm_version }}
    - libhwloc 1.*
    - libtool

test:
  requires:
    - pyopencl
    - curl
    - osx-pocl-opencl  # [osx]

  commands:
    - test -f $PREFIX/lib64/libpocl.so  # [linux]
    - test -f $PREFIX/lib/libOpenCL.dylib  # [osx]
    - curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py
    - python demo.py

about:
  home: http://portablecl.org/
  license: MIT
  license_file: LICENSE
  summary: 'Portable Computing Language -- a CPU OpenCL implementation'
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
