{% set name = "pocl" %}
{% set version = "1.5" %}
{% set build_number = 5 %}
{% set sha256 = "4fcf4618171727d165fc044d465a66e3119217bb4577a97374f94fcd8aed330e" %}
{% set llvm_version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - patches/gh814.patch
      - patches/gh819.patch
      - patches/gh822.patch
      - patches/gh824.patch
      - patches/gh-fdde088.patch
      - patches/gh821.patch
      - patches/gh-459d0bb.patch
      - patches/gh834.patch
      - patches/gh836.patch
      - patches/gh-804bc73.patch
      - patches/gh838.patch

build:
  number: {{ build_number }}
  skip: true  # [win]
  merge_build_host: true  # [cxx_compiler=='gxx']
  script_env:     # [enable_cuda]
    - CUDA_HOME   # [enable_cuda]

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc
    - llvmdev =={{ llvm_version }}
    - clangdev =={{ llvm_version }}
    - lld =={{ llvm_version }}
    - zlib                               # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - {{ pin_compatible('libhwloc') }}

test:
  requires:
    - pyopencl  # [x86_64]
    - curl  # [x86_64]
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    # Remove apple icd so that only pocl is found
    - rm $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
    - export OCL_ICD_DEBUG=15                     # [linux]
    - curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py  # [x86_64]
    - python demo.py  # [x86_64]

outputs:
  - name: pocl

  - name: pocl-cuda
    build:
      skip: True   # [not enable_cuda]
    script: install-cuda.sh
    requirements:
      host:
        - {{ pin_subpackage("pocl", exact=True) }}
      run:
        - {{ pin_subpackage("pocl", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda.so     # [unix]

about:
  home: http://portablecl.org/
  license: MIT
  license_file:
    - LICENSE
    - LLVM-License.txt
  summary: Portable Computing Language -- a CPU OpenCL implementation
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
