{% set name = "pocl" %}
{% set version = "1.6" %}
{% set build_number = 0 %}
{% set sha256 = "b0a4c0c056371b6f0db726b88fbb76bbee94948fb2abd4dbc8d958f7c42f766c" %}
{% set llvm_version = "10.0.1" %}
{% set osx_llvm_version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pocl/pocl/archive/v{{ version.replace(".rc", "-RC") }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - gh887.diff

build:
  number: {{ build_number }}
  skip: true  # [win]
  merge_build_host: true  # [cxx_compiler=='gxx']
  script_env:     # [enable_cuda]
    - CUDA_HOME   # [enable_cuda]

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('cxx') }}
    - llvmdev {{ llvm_version }}.*       # [build_platform != target_platform and not osx]
    - clangdev {{ llvm_version }}.*      # [build_platform != target_platform and not osx]
    - llvmdev {{ osx_llvm_version }}.*       # [build_platform != target_platform and osx]
    - clangdev {{ osx_llvm_version }}.*      # [build_platform != target_platform and osx]
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc

    - llvmdev {{ llvm_version }}.*  # [not osx]
    - clangdev {{ llvm_version }}.*  # [not osx]
    - llvm {{ llvm_version }}.*  # [not osx]
    - libclang-cpp {{ llvm_version }}.*  # [not osx]

    - llvmdev {{ osx_llvm_version }}.*  # [osx]
    - clangdev {{ osx_llvm_version }}.*  # [osx]
    - llvm {{ osx_llvm_version }}.*  # [osx]
    - libclang-cpp {{ osx_llvm_version }}.*  # [osx]

    - zlib                               # [osx]
    - ld64 >=530                         # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - ld64 >=530                         # [osx]
    - {{ pin_compatible('libhwloc') }}

test:
  requires:
    - pyopencl
    - curl
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    # Remove apple icd so that only pocl is found
    - rm $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
    - export OCL_ICD_DEBUG=15                     # [linux]
    - curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py
    - python demo.py

outputs:
  - name: pocl

  - name: pocl-cuda
    build:
      skip: True   # [not enable_cuda]
    script: install-cuda.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("pocl", exact=True) }}
        - llvm {{ llvm_version }}.*  # [not osx]
        - llvm {{ osx_llvm_version }}.*  # [osx]
        - libhwloc
      run:
        - {{ pin_subpackage("pocl", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda.so     # [unix]

about:
  home: http://portablecl.org/
  license: MIT
  license_file:
    - LICENSE
    - LLVM-License.txt
  summary: Portable Computing Language -- a CPU OpenCL implementation
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
