{% set name = "pocl" %}
{% set version = "1.2" %}
{% set build_number = 1003 %}
{% set sha256 = "0c43e68f336892f3a64cba19beb99d9212f529bedb77f7879c0331450b982d46" %}
{% set llvm_version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/pocl/pocl.git
    git_rev: v1.3-RC1

    patches:
    # Put binary paths built in pocl into a separate compilation unit
    # so that conda can successfully change them. (If they're not in
    # a separate compilation unit, the compiler has a habit of evaluating
    # strlen() and such at compile time.)
    - paths-in-separate-compilation-unit.patch

build:
  number: {{ build_number }}
  skip: True  # [win]
  merge_build_host: True   # [cxx_compiler=='gxx']

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc
    - libtool
    - llvmdev =={{ llvm_version }}
    - clangdev =={{ llvm_version }}
    - libcxx                             # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - {{ pin_compatible('libhwloc') }}
    - libtool
    - clangdev =={{ llvm_version }}

test:
  #requires:
    #- pyopencl
    #- curl
    #- osx-pocl-opencl  # [osx]

  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    #- curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py
    #- python demo.py

about:
  home: http://portablecl.org/
  license: MIT
  license_file: LICENSE
  summary: 'Portable Computing Language -- a CPU OpenCL implementation'
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
