{% set name = "pocl" %}
{% set version = "1.7" %}
{% set build_number = 2 %}
{% set sha256 = "5f6bbc391ba144bc7becc3b90888b25468460d5aa6830f63a3b066137e7bfac3" %}

{% set llvm_version = "11.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pocl/pocl/archive/v{{ version.replace(".rc", "-RC") }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # pocl/pocl#936
      - patches/test-dlopen-fix-apple.diff
      - patches/gh963.patch

build:
  number: {{ build_number }}
  skip: true  # [win]
  merge_build_host: true  # [cxx_compiler=='gxx']
  script_env:   # [enable_cuda]
    - CUDA_HOME   # [enable_cuda]

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('cxx') }}
    
    - llvmdev {{ llvm_version }}.*       # [build_platform != target_platform]
    - clangdev {{ llvm_version }}.*      # [build_platform != target_platform]
    - clang-{{ llvm_version.split(".")[0] }}           # [osx]
  host:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - libhwloc

    - llvmdev {{ llvm_version }}.*
    - clangdev {{ llvm_version }}.*
    - llvm {{ llvm_version }}.*
    - libclang-cpp {{ llvm_version }}.*

    - zlib                               # [osx]
    - ld64 >=530                         # [osx]
  run:
    - ocl-icd                            # [linux]
    - khronos-opencl-icd-loader          # [osx]
    - ld64 >=530                         # [osx]
    - {{ pin_compatible('libhwloc') }}

test:
  requires:
    - pyopencl
    - curl
  commands:
    - test -f $PREFIX/lib/libpocl${SHLIB_EXT}     # [unix]
    # Remove apple icd so that only pocl is found
    - rm -f $PREFIX/etc/OpenCL/vendors/apple.icd     # [osx]
    - export OCL_ICD_DEBUG=15                     # [linux]
    - curl -O https://raw.githubusercontent.com/inducer/pyopencl/master/examples/demo.py
    - python demo.py

outputs:
  - name: pocl

  - name: pocl-cuda
    build:
      skip: true  # [not enable_cuda]
    script: install-cuda.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("pocl", exact=True) }}
        - llvm {{ llvm_version }}.*
        - libhwloc
      run:
        - {{ pin_subpackage("pocl", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pocl/libpocl-devices-cuda.so     # [unix]

about:
  home: http://portablecl.org/
  license: MIT
  license_file:
    - LICENSE
    - LLVM-License.txt
  summary: Portable Computing Language -- a CPU OpenCL implementation
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
    - isuruf
    - matthiasdiener
