provider: {linux_aarch64: native, linux_ppc64le: azure}
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
test: native
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
