build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: native
  linux_ppc64le: azure
test: native
azure:
  store_build_artifacts: true

# The next two lines are necessary to support the ppc64le build,
# whose CUDA (v10.2) image is outdated.
conda_install_tool: conda
conda_solver: classic
